### ISSUE TITLE
첫번째 이슈 입력

### ISSUE THREAD

**Issue by newumare** [newumare/calculator#1]
그냥 글꼴

<b> 진한 글꼴? </b>

**Comment by yckimn** [comment]
이슈에 댓글을 남기는 게 가능 (collaborator도 접근 가능)

**Comment by newumare** [comment]
셀프 댓글도 물론 가능하고...

드래그 & 드랍으로 파일 업로드도 가능

[프리 소프트웨어 프로젝트에서의 품질 관리 관행과 문제점.pdf](https://github.com/newumare/calculator/files/2182637/default.pdf)

![image](https://user-images.githubusercontent.com/4222578/42545570-c22b95b0-84f3-11e8-9458-bc9a016c6ced.png)
클립보드로 이미지 붙이는 거도 가능??? (위에 링크 클립보드 copy & paste 한건데??)

**Comment by newumare** [comment]
헐?
이미지 copy-paste 가능... 멋진 걸??
